WIP: first stab
prooph/pdo-snapshot-store pull request #11
Opened 2017-04-04 19:46 UTC by basz

https://github.com/prooph/snapshot-store/issues/6

2017-04-05 07:07 UTC, prolic requested changes
We also need a way to put this into our provided factories, so the setup is easy.

2017-04-05 07:07 UTC, prolic commented on src/SerializerStrategy.php
> +interface SerializerStrategy
Two things:

1) Rename `SerializerStrategy` => `Serializer`
2) Move to snapshot-store repository, so it can be reused accross different snapshot-store implementations.

2017-04-05 07:07 UTC, prolic commented on src/SerializerStrategy.php
> +    public function deserialize(string $data);
rename to `unserialize`

2017-04-05 07:07 UTC, prolic commented on src/Serializer.php
> +        if ($serializer && $deserialize) {
`if (null !== $serializeCallback && null !== $unserializeCallback)` is much faster.

see https://3v4l.org/QaoTI

2017-04-05 07:07 UTC, prolic commented on src/Serializer.php
> +final class DefaultSerializerStrategy implements SerializerStrategy
Rename to `CallbackSerializer`

2017-04-05 10:15 UTC, basz commented
should we move CallbackSerializer to the main repo too? That way the docs I wrote there make more sense :-)

2017-04-05 10:42 UTC, prolic commented
Yes

Am 05.04.2017 18:15 schrieb "Bas Kamer" <notifications@github.com>:

> should we move CallbackSerializer to the main repo too? That way the docs
> I wrote there make more sense :-)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/prooph/pdo-snapshot-store/pull/11#issuecomment-291817570>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAYEvNuvWo7kBCdy5O_3KY_P2eL9CwN-ks5rs2msgaJpZM4MzVqV>
> .
>

2017-04-05 11:03 UTC, basz commented
review [this](https://github.com/prooph/snapshot-store/pull/7) one first please

2017-04-05 15:48 UTC, prolic requested changes

2017-04-05 15:48 UTC, prolic commented on src/Container/PdoSnapshotStoreFactory.php
> +        $serializer = $container->has($config['serialize']) ? $container->get($config['serialize']) : new CallbackSerializer(null, null);
`serializer` instead of `serialize`

2017-04-05 15:48 UTC, prolic commented on src/Container/PdoSnapshotStoreFactory.php
> +            'serializer' => Serializer::class,
'serializer' => new CallbackSerializer()

2017-04-05 15:48 UTC, prolic commented on src/Container/PdoSnapshotStoreFactory.php
> +        $serializer = $container->has($config['serialize']) ? $container->get($config['serialize']) : new CallbackSerializer(null, null);
`$container->has()` check can be removed, the serializer is always provided through defaultConfig, if the container is wrongly configured, an exception is thrown, that's good enough.

2017-04-05 15:48 UTC, prolic commented on src/PdoSnapshotStore.php
> +        Serializer $serializer
`Serializer $serializer = null` to not break BC

2017-04-05 15:48 UTC, prolic commented on src/PdoSnapshotStore.php
> +        $this->serializer = $serializer;
create default serializer if null provided

2017-04-05 15:48 UTC, prolic commented on src/SerializerStrategy.php
> +interface SerializerStrategy
class can now be removed as the interface now belongs to snapshot-store

2017-04-05 18:00 UTC, basz commented on src/Container/PdoSnapshotStoreFactory.php
> +        $serializer = $container->has($config['serialize']) ? $container->get($config['serialize']) : new CallbackSerializer(null, null);
I don't get that. If `'serializer' => new CallbackSerializer()` is in the defaultOptions how would one override (get it from the container) it without some sort of switch?

```
$serializer = $config['serializer'] instanceof Serializer ? $config['serializer'] : $container->get($config['serialize']);
```

2017-04-06 07:19 UTC, prolic commented
You also do https://github.com/prooph/mongodb-snapshot-store/ ?

2017-04-06 07:23 UTC, merged