adds PKs to schema's
prooph/pdo-snapshot-store pull request #24
Opened 2018-04-13 20:20 UTC by basz

fixes #23

2018-04-14 09:11 UTC, prolic requested changes
Can you also put the ALTER TABLE statements in readme for users who need to upgrade the database manually? Also maybe a note, that alternatively they can simply drop snapshot tables and reset snapshotter projection?

2018-04-14 09:11 UTC, prolic commented on scripts/mysql_snapshot_table.sql
>    UNIQUE KEY `ix_aggregate_id` (`aggregate_id`)
unique can be removed

2018-04-14 12:12 UTC, basz commented
done

2018-04-15 08:39 UTC, prolic approved these changes

2018-04-15 08:39 UTC, merged